### PR TITLE
feat(cli): Add callbacks to cli

### PR DESCRIPTION
**Pull request by lake2**
Closes https://github.com/swc-project/pkgs/issues/55

I rename `packages/cli/src/swc/index.ts` to `packages/cli/src/swc/bin.ts`, and export `swcDir` function via new `packages/cli/src/swc/index.ts`

add doc here: https://github.com/swc-project/website/pull/261

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
Can you add some tests for this?

**Comment by lake2** [comment]
> Can you add some tests for this?

I tried, I can add tests for `watch=false` and `sync=true` options.
It's hard to mock worker and file change watcher.

**Comment by kdy1** [comment]
I think tests to ensure that `onSuccess` and `onFail` are called are enough

**Comment by lake2** [comment]
> I think tests to ensure that `onSuccess` and `onFail` are called are enough

Sure. I will accomplish it later.

**Comment by lake2** [comment]
> I think tests to ensure that `onSuccess` and `onFail` are called are enough

Test cases update. Can you release a beta version for testing?

**Review by kdy1 — APPROVED** [review]
As I don't want to delete git tag or publish from a PR branch, I'll merge it first and revert/invert it as needed

**Pull request merged**
