### PR TITLE
fix: change stderr to stdout

### PR DESCRIPTION
**Pull request by SocketSomeone**

### CODE REVIEW

**Comment by kdy1** [comment]
Can you describe?

**Review by magic-akari — CHANGES_REQUESTED** [review]
The use of `stderr` for outputting information is intentional and by design. 
Could you explain why you wish to switch to `stdout`?

**Comment by SocketSomeone** [comment]
> Can you describe the reason?

> The use of `stderr` for outputting information is intentional and by design. Could you explain why you wish to switch to `stdout`?
It seems that the current version of the application is using the wrong stream for its messages. In our company, we rely on reading logs from stderr to detect issues and stop the build when something goes wrong. However, it feels odd to encounter "successful errors" in the error stream. *shrug*

**Comment by SocketSomeone** [comment]
- `stdout (Standard Output)`: Used for regular program output, particularly results or information that is the intended product of the program's execution.

- `stderr (Standard Error)`: Reserved for diagnostic messages, errors, warnings, or any information unrelated to the normal output.

Messages like "Successfully compiled ${filename} with swc" looks as information of program execution.

**Comment by magic-akari** [comment]
> It seems that the current version of library is using the wrong stream for its messages. In our company, we rely on reading logs from stderr to detect issues and stop the build when something goes wrong. However, it feels odd to encounter "successful errors" in the error stream. _shrug_

I recommend using exit code detection instead of relying on stderr to determine errors. This is because `stderr` output could be tips, warnings, or any other information.

> * `stdout (Standard Output)`: Used for regular program output, particularly results or information that is the intended product of the program's execution.
> * `stderr (Standard Error)`: Reserved for diagnostic messages, errors, warnings, or any information unrelated to the normal output.
> 
> Messages like "Successfully compiled ${filename} with swc" looks as information of program execution.

What you cited is correct; for the SWC CLI, `stdout` should only be the compilation output.
If the output is a file, `stdout` should be empty. 

The "Successfully compiled" message, however, is a notification unrelated to the normal output and is expected to be emitted to `stderr`.

**Comment by magic-akari** [comment]
> *Return zero exit code on success, non-zero on failure.* Exit codes are how scripts determine whether a program succeeded or failed, so you should report this correctly. Map the non-zero exit codes to the most important failure modes.
> 
> *Send output to `stdout`.* The primary output for your command should go to `stdout`. Anything that is machine readable should also go to `stdout`—this is where piping sends things by default.
> 
> *Send messaging to `stderr`.* Log messages, errors, and so on should all be sent to `stderr`. This means that when commands are piped together, these messages are displayed to the user and not fed into the next command.

This is an excellent CLI design guide, which I believe is worth referring to: https://clig.dev/

**Comment by SocketSomeone** [comment]
@magic-akari Thank you  for attention and advice! We will try to use exit code! I think it can be closed.

**Pull request closed without merging**
