### PR TITLE
fix(cli): Redirect messages to stderr

### PR DESCRIPTION
**Pull request by magic-akari**

### CODE REVIEW

**Review by kdy1 — DISMISSED** [review]

**Comment by kdy1** [comment]
Can you rebase?

**Review by kdy1 — APPROVED** [review]

**Comment by rathpc** [comment]
Is there any context about why this change was made?

**Comment by kdy1** [comment]
Error messages should go to the stderr. It’s correct default, so we fixed it.

**Comment by Reflejo** [comment]
That makes sense, although this PR also changed a non-error message, aka:

```patch
-            console.log(message, duration.toFixed(2));
+            stderr.write(message);
```

which in turned broke nx https://github.com/nrwl/nx/blob/master/packages/js/src/utils/swc/compile-swc.ts#L95 - Pretty nasty the way they check for success (instead of exit code) but it broke nonetheless

**Comment by rathpc** [comment]
> That makes sense, although this PR also changed a non-error message, aka:
> 
> ```patch
> -            console.log(message, duration.toFixed(2));
> +            stderr.write(message);
> ```
> 
> which in turned broke nx https://github.com/nrwl/nx/blob/master/packages/js/src/utils/swc/compile-swc.ts#L95 - Pretty nasty the way they check for success (instead of exit code) but it broke nonetheless

This was the reason I ended up here actually. Attempted updating swc in am NX project and learned pretty quick it did not work as expected despite a successful build.

**Comment by kdy1** [comment]
> -            console.log(message, duration.toFixed(2));

This is a log, so it should go to `stderr`

**Pull request merged**
